<?php

/**
 * @file
 * Primary module hooks for vehicle_custom module.
 */
function vehicle_custom_preprocess_node(array &$variables) {
  $node = $variables['node'];

  // Check if the content type is the one we want to target.
  // Load the vehicle lookup service.
  $vehicle_lookup_service = \Drupal::service('vehicle_custom.vehicle_lookup');

  // Get the vehicle title by node ID.
  $vehicle_title = $vehicle_lookup_service->getVehicleTitleByNid(3);

  // Add the vehicle title to the template variables.
  $variables['vehicle_title'] = $vehicle_title;
}
