<?php

/**
 * @file
 * Primary module hooks for vehicle_custom module.
 */
function vehicle_custom_preprocess_node(array &$variables) {
  // Load the vehicle lookup service.
  $vehicle_lookup_service = \Drupal::service('vehicle_custom.vehicle_lookup');
  // Get vehicle title by node ID.
  $vehicle_title = $vehicle_lookup_service->getNodeTitle(3);
  // Add vehicle title to template variables.
  $variables['vehicle_title'] = $vehicle_title;
}
